[package]
name = "satty"
version = "0.11.2"
edition = "2021"
authors = ["Matthias Gabriel <gabm+aur@mailbox.org>"]
description = "Modern Screenshot Annotation. A Screenshot Annotation Tool inspired by Swappy and Flameshot."
homepage = "https://github.com/gabm/satty"
repository = "https://github.com/gabm/satty"
license = "MPL-2.0"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "assets/",
]


[dependencies]
relm4 = { version = "0.6.2", features = ["macros", "libadwaita", "gnome_42"] }
tokio = { version = "1.32.0", features = ["full"] }
gdk-pixbuf = "0.17.2"

# error handling
anyhow = "1.0"
thiserror = "1.0"

# command line
clap = { version = "4.4.10", features = ["derive"] }

# configuration file
xdg = "^2.5"
toml = "0.8.8"
serde = "1.0"
serde_derive = "1.0"
hex_color = {version = "3", features = ["serde"]}
chrono = "0.4.31"

# opengl rendering backend
femtovg = "0.8"
libloading = "0.8"
epoxy = "0.1.0"
glow = "0.13.1"
glib-macros = "0.19.2"
glib = "0.19.2"
resource = "0.5.0"  # font emedding

[dependencies.relm4-icons]
version = "0.6.0"
features = [
  "pen-regular",
  "color-regular",
  "cursor-regular",
  "number-circle-1-regular",
  "drop-regular",
  "arrow-redo-filled",
  "arrow-undo-filled",
  "save-regular",
  "copy-regular",
  "text-case-title-regular",
  "text-font-regular",
  "minus-large",
  "checkbox-unchecked-regular",
  "crop-filled",
  "arrow-up-right-filled",
  "rectangle-landscape-regular",
]

[build-dependencies]
clap = { version = "4.4.10", features = ["derive"] }
clap_complete = "4.4.4"
clap_complete_nushell = "4.4.2"
clap_complete_fig = "4.4.2"
